sudo: false

language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failtures:
    - php: hhvm

before_script:
  - composer --prefer-source --dev install

script: phpunit -v -c phpunit.xml --coverage-text